In [ ]:
import pandas as pd
s = pd.Series([1, 2, 3])
print(s)

0    1
1    2
2    3
dtype: int64


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [ ]:
import pandas as pd
s=pd.Series([1,2,100],index=["a","b","c"])
print(s)

a      1
b      2
c    100
dtype: int64


In [ ]:
import math

print("Floor of 5.7:", math.floor(5.7))
print("Ceil of 5.2:", math.ceil(5.2))
print("Square root of 16:", math.sqrt(16))
print("Integer square root of 17:", math.isqrt(17))
print("GCD of 48 and 18:", math.gcd(48, 18))


Floor of 5.7: 5
Ceil of 5.2: 6
Square root of 16: 4.0
Integer square root of 17: 4
GCD of 48 and 18: 6


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Dimensions (ndim):", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Sum of elements:", np.sum(arr))
print("Mean of elements:", np.mean(arr))
print("Sorted array:\n", np.sort(arr))
print("Sine of elements (in radians):\n", np.sin(arr))


Array:
 [[1 2 3]
 [4 5 6]]
Dimensions (ndim): 2
Shape: (2, 3)
Size: 6
Sum of elements: 21
Mean of elements: 3.5
Sorted array:
 [[1 2 3]
 [4 5 6]]
Sine of elements (in radians):
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [ ]:
from numpy.linalg import det, eig

matrix = np.array([[4, 2], [1, 3]])

print("Matrix:\n", matrix)
print("Determinant:", det(matrix))

eigenvalues, eigenvectors = eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Matrix:
 [[4 2]
 [1 3]]
Determinant: 10.000000000000002
Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [ ]:
one_d_list = [i for i in range(1, 13)]  # list with 12 elements
array_1d = np.array(one_d_list)

array_2d = array_1d.reshape(3, 4)
array_3d = array_1d.reshape(2, 2, 3)

print("Original 1D array:", array_1d)
print("Reshaped to 2D (3x4):\n", array_2d)
print("Reshaped to 3D (2x2x3):\n", array_3d)


Original 1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped to 2D (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped to 3D (2x2x3):
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
zeros_array = np.zeros((2, 3))
ones_array = np.ones((3, 3))
identity_matrix = np.eye(4)
random_matrix = np.random.rand(2, 2)
range_array = np.arange(1, 10)

print("Zeros array:\n", zeros_array)
print("Ones array:\n", ones_array)
print("Identity matrix:\n", identity_matrix)
print("Random matrix:\n", random_matrix)
print("Range array:\n", range_array)


Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random matrix:
 [[0.33076207 0.19454364]
 [0.74902355 0.11116229]]
Range array:
 [1 2 3 4 5 6 7 8 9]


In [ ]:
from scipy import linalg

matrix2 = np.array([[6, 1], [4, -2]])
det_value = linalg.det(matrix2)

print("Matrix:\n", matrix2)
print("Determinant using scipy:", det_value)


Matrix:
 [[ 6  1]
 [ 4 -2]]
Determinant using scipy: -16.0


In [ ]:
eigvals, eigvecs = linalg.eig(matrix2)

print("Eigenvalues using scipy:", eigvals)
print("Eigenvectors using scipy:\n", eigvecs)


Eigenvalues using scipy: [ 6.47213595+0.j -2.47213595+0.j]
Eigenvectors using scipy:
 [[ 0.90427877 -0.11722026]
 [ 0.42694252  0.99310594]]


In [ ]:
import pandas as pd
s=pd.Series([1,2,100],index=["a","b","c"])
print(s["b"])

2


In [ ]:
import pandas as pd
s=pd.Series([1,2,100],index=[100,101,102])
print(s)

100      1
101      2
102    100
dtype: int64


In [ ]:
import pandas as pd
s=pd.Series([1,2,100],index=["a","b","c"])
print(s.index)
print(s.values)

Index(['a', 'b', 'c'], dtype='object')
[  1   2 100]


In [ ]:
import pandas as pd
import numpy as np
a=np.array([1,2,3,4])
s=pd.Series([1,2,3,4])
print(a==s.values)

[ True  True  True  True]


In [ ]:
import pandas as pd
import numpy as np
a=np.array([1,2,3,4])
s=pd.Series([1,2,3,4])
print(a==s)

0    True
1    True
2    True
3    True
dtype: bool


In [ ]:
import pandas as pd
import numpy as np
a=np.array([1,2,3,4])
s=pd.Series([1,2,3,4])
print(a==s)

0    True
1    True
2    True
3    True
dtype: bool


In [ ]:
import pandas as pd
data={'name':['kanishka','seetha'],'age':[20,25],'marks':[100,102]}
df=pd.DataFrame(data)
print(df)

       name  age  marks
0  kanishka   20    100
1    seetha   25    102


In [ ]:
import pandas as pd
data={'name':['kanishka','seetha'],'age':[20,25],'marks':[100,102]}
df=pd.DataFrame(data)
print(df)

       name  age  marks
0  kanishka   20    100
1    seetha   25    102


In [ ]:
import pandas as pd
df=pd.read_csv('data.csv')
print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [ ]:
from sklearn.datasets import load_iris
data=load_iris()
print(data.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [ ]:
from sklearn.datasets import load_iris,load_diabetes
data=load_iris()
print(data.keys())
newdata=load_diabetes()
print(newdata.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])


In [ ]:
from sklearn.datasets import load_iris,load_diabetes
data=load_iris()
print(data.feature_names)
newdata=load_diabetes()
print(newdata.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']


In [ ]:
from sklearn.datasets import load_iris,load_diabetes
data=load_iris()
df=pd.DataFrame(data.data,columns=data.feature_names)
print(df.head())
newdata=load_diabetes()
print(newdata.keys())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])


In [ ]:
from sklearn.datasets import load_iris, load_diabetes
import pandas as pd
data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target
print(df.head())
newdata = load_diabetes()
print(newdata.keys())


   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  
dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])


In [ ]:
from sklearn.datasets import load_iris,load_diabetes
data=load_iris()
df=pd.DataFrame(data.data,columns=data.feature_names)
df['target']=data.target
print(df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  
